# -*- coding: utf-8 -*-
"""F1Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_coKcrQIFY4JOWigWEGN4CxP3gccUDc
"""

import pandas as pd
import numpy as np
import os

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Load CSV files
races = pd.read_csv("races.csv")
drivers = pd.read_csv("drivers.csv")
constructors = pd.read_csv("constructors.csv")
results = pd.read_csv("results.csv")
lap_times = pd.read_csv("lap_times.csv")
pit_stops = pd.read_csv("pit_stops.csv")
qualifying = pd.read_csv("qualifying.csv")

print("Races:", races.shape)
print("Drivers:", drivers.shape)
print("Constructors:", constructors.shape)
print("Results:", results.shape)
print("Lap times:", lap_times.shape)
print("Pit stops:", pit_stops.shape)
print("Qualifying:", qualifying.shape)

"""#### Check dataset columns"""

print("Races columns:")
print(races.columns.tolist())

print("\nDrivers columns:")
print(drivers.columns.tolist())

print("\nConstructors columns:")
print(constructors.columns.tolist())

print("\nResults columns:")
print(results.columns.tolist())

print("\nLap times columns:")
print(lap_times.columns.tolist())

print("\nPit stops columns:")
print(pit_stops.columns.tolist())

print("\nQualifying columns:")
print(qualifying.columns.tolist())

"""#### Prepare driver and constructor names"""

# Create full driver name
drivers_clean = drivers.copy()

drivers_clean["driver_name"] = (
    drivers_clean["forename"].astype(str) + " " + drivers_clean["surname"].astype(str)
)

drivers_clean = drivers_clean[
    ["driverId", "driverRef", "code", "driver_name", "nationality"]
]

drivers_clean.head()

# Prepare constructor/team names
constructors_clean = constructors.copy()

constructors_clean = constructors_clean[
    ["constructorId", "constructorRef", "name", "nationality"]
].rename(columns={
    "name": "constructor_name",
    "nationality": "constructor_nationality"
})

constructors_clean.head()

"""#### Merge race results with races, drivers and constructors"""

# 1. Filter races from 2020 to 2024
races_5yr = races[(races["year"] >= 2020) & (races["year"] <= 2024)].copy()

# 2. Create driver full name
drivers_clean = drivers.copy()
drivers_clean["driver_name"] = (
    drivers_clean["forename"].astype(str) + " " + drivers_clean["surname"].astype(str)
)

drivers_clean = drivers_clean[
    ["driverId", "driverRef", "code", "driver_name", "nationality"]
]

# 3. Prepare constructor names
constructors_clean = constructors.copy()
constructors_clean = constructors_clean[
    ["constructorId", "constructorRef", "name", "nationality"]
].rename(columns={
    "name": "constructor_name",
    "nationality": "constructor_nationality"
})

# 4. Merge results with race information
results_5yr = results.merge(
    races_5yr[["raceId", "year", "round", "name", "date"]],
    on="raceId",
    how="inner"
)

results_5yr = results_5yr.rename(columns={"name": "race_name"})

# 5. Merge driver information
results_5yr = results_5yr.merge(
    drivers_clean,
    on="driverId",
    how="left"
)

# 6. Merge constructor information
results_5yr = results_5yr.merge(
    constructors_clean,
    on="constructorId",
    how="left"
)

# 7. Convert important columns to numeric
results_5yr["points"] = pd.to_numeric(results_5yr["points"], errors="coerce")
results_5yr["grid"] = pd.to_numeric(results_5yr["grid"], errors="coerce")
results_5yr["positionOrder"] = pd.to_numeric(results_5yr["positionOrder"], errors="coerce")
results_5yr["laps"] = pd.to_numeric(results_5yr["laps"], errors="coerce")

results_5yr.head()

# Merge results with race information
results_5yr = results.merge(
    races_5yr[["raceId", "year", "round", "name", "date"]],
    on="raceId",
    how="inner"
)

results_5yr = results_5yr.rename(columns={"name": "race_name"})

# Merge driver information
results_5yr = results_5yr.merge(
    drivers_clean,
    on="driverId",
    how="left"
)

# Merge constructor information
results_5yr = results_5yr.merge(
    constructors_clean,
    on="constructorId",
    how="left"
)

# Convert important columns to numeric
results_5yr["points"] = pd.to_numeric(results_5yr["points"], errors="coerce")
results_5yr["grid"] = pd.to_numeric(results_5yr["grid"], errors="coerce")
results_5yr["positionOrder"] = pd.to_numeric(results_5yr["positionOrder"], errors="coerce")
results_5yr["laps"] = pd.to_numeric(results_5yr["laps"], errors="coerce")

results_5yr.head()

"""#### Basic summary"""

print("Last 5 seasons results shape:", results_5yr.shape)
print("Years:", sorted(results_5yr["year"].unique()))
print("Total races:", results_5yr["raceId"].nunique())
print("Total drivers:", results_5yr["driver_name"].nunique())
print("Total constructors:", results_5yr["constructor_name"].nunique())

"""#### Driver points analysis"""

driver_points_5yr = (
    results_5yr
    .groupby("driver_name")["points"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

driver_points_5yr.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    data=driver_points_5yr.head(10),
    x="points",
    y="driver_name"
)

plt.title("Top 10 Drivers by Total Points: 2020–2024")
plt.xlabel("Total Points")
plt.ylabel("Driver")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Driver yearly trend"""

driver_points_year = (
    results_5yr
    .groupby(["year", "driver_name"])["points"]
    .sum()
    .reset_index()
)

top_5_drivers = driver_points_5yr.head(5)["driver_name"].tolist()

top_driver_trend = driver_points_year[
    driver_points_year["driver_name"].isin(top_5_drivers)
]

top_driver_trend.head()

plt.figure(figsize=(12, 6))

sns.lineplot(
    data=top_driver_trend,
    x="year",
    y="points",
    hue="driver_name",
    marker="o"
)

plt.title("Top Driver Points Trend: 2020–2024")
plt.xlabel("Season")
plt.ylabel("Total Points")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Constructor points analysis"""

constructor_points_5yr = (
    results_5yr
    .groupby("constructor_name")["points"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

constructor_points_5yr

plt.figure(figsize=(12, 6))

sns.barplot(
    data=constructor_points_5yr,
    x="points",
    y="constructor_name"
)

plt.title("Constructor Points: 2020–2024")
plt.xlabel("Total Points")
plt.ylabel("Constructor")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Constructor yearly trend"""

constructor_points_year = (
    results_5yr
    .groupby(["year", "constructor_name"])["points"]
    .sum()
    .reset_index()
)

top_5_teams = constructor_points_5yr.head(5)["constructor_name"].tolist()

top_team_trend = constructor_points_year[
    constructor_points_year["constructor_name"].isin(top_5_teams)
]

top_team_trend.head()

plt.figure(figsize=(12, 6))

sns.lineplot(
    data=top_team_trend,
    x="year",
    y="points",
    hue="constructor_name",
    marker="o"
)

plt.title("Top Constructor Points Trend: 2020–2024")
plt.xlabel("Season")
plt.ylabel("Total Points")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Race wins by driver"""

wins_5yr = results_5yr[results_5yr["positionOrder"] == 1].copy()

driver_wins_5yr = (
    wins_5yr
    .groupby("driver_name")
    .size()
    .sort_values(ascending=False)
    .reset_index(name="wins")
)

driver_wins_5yr.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    data=driver_wins_5yr.head(10),
    x="wins",
    y="driver_name"
)

plt.title("Top Race Winners: 2020–2024")
plt.xlabel("Number of Wins")
plt.ylabel("Driver")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Race wins by constructor"""

constructor_wins_5yr = (
    wins_5yr
    .groupby("constructor_name")
    .size()
    .sort_values(ascending=False)
    .reset_index(name="wins")
)

constructor_wins_5yr

plt.figure(figsize=(12, 6))

sns.barplot(
    data=constructor_wins_5yr,
    x="wins",
    y="constructor_name"
)

plt.title("Constructor Race Wins: 2020–2024")
plt.xlabel("Number of Wins")
plt.ylabel("Constructor")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Grid position vs final race position"""

grid_vs_finish_5yr = results_5yr[results_5yr["grid"] > 0].copy()

grid_vs_finish_5yr[["year", "race_name", "driver_name", "constructor_name", "grid", "positionOrder"]].head()

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=grid_vs_finish_5yr,
    x="grid",
    y="positionOrder",
    hue="year"
)

plt.title("Grid Position vs Final Race Position: 2020–2024")
plt.xlabel("Starting Grid Position")
plt.ylabel("Final Race Position")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Position gain/loss analysis"""

position_change = grid_vs_finish_5yr.copy()

# Positive value means driver finished better than starting position
position_change["positions_gained"] = position_change["grid"] - position_change["positionOrder"]

driver_position_gain = (
    position_change
    .groupby("driver_name")["positions_gained"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

driver_position_gain.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    data=driver_position_gain.head(10),
    x="positions_gained",
    y="driver_name"
)

plt.title("Average Positions Gained by Driver: 2020–2024")
plt.xlabel("Average Positions Gained")
plt.ylabel("Driver")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Pit stop data preparation"""

pit_5yr = pit_stops.merge(
    races_5yr[["raceId", "year", "name"]],
    on="raceId",
    how="inner"
)

pit_5yr = pit_5yr.rename(columns={"name": "race_name"})

pit_5yr = pit_5yr.merge(
    drivers_clean[["driverId", "driver_name"]],
    on="driverId",
    how="left"
)

pit_5yr["milliseconds"] = pd.to_numeric(pit_5yr["milliseconds"], errors="coerce")
pit_5yr["pit_seconds"] = pit_5yr["milliseconds"] / 1000

pit_5yr.head()

"""#### Fastest average pit stops"""

avg_pit_driver = (
    pit_5yr
    .groupby("driver_name")["pit_seconds"]
    .mean()
    .sort_values()
    .reset_index()
)

avg_pit_driver.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    data=avg_pit_driver.head(10),
    x="pit_seconds",
    y="driver_name"
)

plt.title("Fastest Average Pit Stop Duration by Driver: 2020–2024")
plt.xlabel("Average Pit Stop Time Seconds")
plt.ylabel("Driver")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Pit stop trend by year"""

pit_year_trend = (
    pit_5yr
    .groupby("year")["pit_seconds"]
    .mean()
    .reset_index()
)

pit_year_trend

plt.figure(figsize=(10, 5))

sns.lineplot(
    data=pit_year_trend,
    x="year",
    y="pit_seconds",
    marker="o"
)

plt.title("Average Pit Stop Duration Trend: 2020–2024")
plt.xlabel("Season")
plt.ylabel("Average Pit Stop Seconds")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Lap time data preparation"""

laps_5yr = lap_times.merge(
    races_5yr[["raceId", "year", "name"]],
    on="raceId",
    how="inner"
)

laps_5yr = laps_5yr.rename(columns={"name": "race_name"})

laps_5yr = laps_5yr.merge(
    drivers_clean[["driverId", "driver_name"]],
    on="driverId",
    how="left"
)

laps_5yr["milliseconds"] = pd.to_numeric(laps_5yr["milliseconds"], errors="coerce")
laps_5yr["lap_seconds"] = laps_5yr["milliseconds"] / 1000

laps_5yr.head()

"""#### Lap time comparison for selected race"""

# Change these values if needed
selected_year = 2024
selected_race = "British Grand Prix"

race_laps = laps_5yr[
    (laps_5yr["year"] == selected_year) &
    (laps_5yr["race_name"] == selected_race)
].copy()

race_laps["driver_name"].unique()[:10]

selected_drivers = [
    "Lewis Hamilton",
    "Max Verstappen",
    "Lando Norris"
]

selected_laps = race_laps[
    race_laps["driver_name"].isin(selected_drivers)
].copy()

selected_laps.head()

plt.figure(figsize=(12, 6))

sns.lineplot(
    data=selected_laps,
    x="lap",
    y="lap_seconds",
    hue="driver_name"
)

plt.title(f"Lap Time Comparison - {selected_race} {selected_year}")
plt.xlabel("Lap Number")
plt.ylabel("Lap Time Seconds")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Lap time consistency"""

plt.figure(figsize=(10, 6))

sns.boxplot(
    data=selected_laps,
    x="driver_name",
    y="lap_seconds"
)

plt.title(f"Lap Time Consistency - {selected_race} {selected_year}")
plt.xlabel("Driver")
plt.ylabel("Lap Time Seconds")
plt.xticks(rotation=30)
plt.grid(axis="y", alpha=0.3)
plt.show()

"""#### Qualifying data preparation"""

qualifying_5yr = qualifying.merge(
    races_5yr[["raceId", "year", "name"]],
    on="raceId",
    how="inner"
)

qualifying_5yr = qualifying_5yr.rename(columns={"name": "race_name"})

qualifying_5yr = qualifying_5yr.merge(
    drivers_clean[["driverId", "driver_name"]],
    on="driverId",
    how="left"
)

qualifying_5yr = qualifying_5yr.merge(
    constructors_clean[["constructorId", "constructor_name"]],
    on="constructorId",
    how="left"
)

qualifying_5yr["position"] = pd.to_numeric(qualifying_5yr["position"], errors="coerce")

qualifying_5yr.head()

"""#### Best average qualifying position"""

avg_qualifying_position = (
    qualifying_5yr
    .groupby("driver_name")["position"]
    .mean()
    .sort_values()
    .reset_index()
)

avg_qualifying_position.head(10)

plt.figure(figsize=(12, 6))

sns.barplot(
    data=avg_qualifying_position.head(10),
    x="position",
    y="driver_name"
)

plt.title("Best Average Qualifying Position: 2020–2024")
plt.xlabel("Average Qualifying Position")
plt.ylabel("Driver")
plt.grid(axis="x", alpha=0.3)
plt.show()

"""#### Qualifying vs race result"""

qualifying_vs_result = qualifying_5yr.merge(
    results_5yr[["raceId", "driverId", "positionOrder", "points"]],
    on=["raceId", "driverId"],
    how="inner"
)

qualifying_vs_result.head()

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=qualifying_vs_result,
    x="position",
    y="positionOrder",
    hue="year"
)

plt.title("Qualifying Position vs Race Finish Position: 2020–2024")
plt.xlabel("Qualifying Position")
plt.ylabel("Race Finish Position")
plt.grid(True, alpha=0.3)
plt.show()

"""#### Save processed datasets for dashboard"""

# Create processed data folder
os.makedirs("processed_data", exist_ok=True)

results_5yr.to_csv("processed_data/results_5yr.csv", index=False)
driver_points_5yr.to_csv("processed_data/driver_points_5yr.csv", index=False)
constructor_points_5yr.to_csv("processed_data/constructor_points_5yr.csv", index=False)
driver_wins_5yr.to_csv("processed_data/driver_wins_5yr.csv", index=False)
constructor_wins_5yr.to_csv("processed_data/constructor_wins_5yr.csv", index=False)
pit_5yr.to_csv("processed_data/pit_5yr.csv", index=False)
laps_5yr.to_csv("processed_data/laps_5yr.csv", index=False)
qualifying_5yr.to_csv("processed_data/qualifying_5yr.csv", index=False)

print("Processed datasets saved successfully.")