# -*- coding: utf-8 -*-
"""F1App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPE8lELUH1v3gaw9LnCYqkTXeBMyDsNT
"""

!python f1analytics.py

import os
os.listdir("processed_data")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile F1app.py
# 
# import os
# import pandas as pd
# import streamlit as st
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# st.set_page_config(
#     page_title="F1 Performance Dashboard",
#     layout="wide"
# )
# 
# # -----------------------------
# # Header
# # -----------------------------
# col_logo, col_title = st.columns([1, 8])
# 
# with col_logo:
#     if os.path.exists("F1logo2.png"):
#         st.image("F1logo2.png", width=110)
#     else:
#         st.markdown("<h1 style='font-size:55px; margin-top:5px;'>F1</h1>", unsafe_allow_html=True)
# 
# with col_title:
#     st.markdown(
#         "<h1 style='margin-top:15px;'>Formula 1 Performance Dashboard: 2020–2024</h1>",
#         unsafe_allow_html=True
#     )
# 
# st.write(
#     "This dashboard uses processed Formula 1 data from the analytics script to analyse driver performance, constructor performance, pit stops, lap times and qualifying results."
# )
# 
# # -----------------------------
# # Load processed data
# # -----------------------------
# @st.cache_data
# def load_processed_data():
#     required_files = {
#         "results": "processed_data/results_5yr.csv",
#         "pit": "processed_data/pit_5yr.csv",
#         "laps": "processed_data/laps_5yr.csv",
#         "qualifying": "processed_data/qualifying_5yr.csv"
#     }
# 
#     missing = [path for path in required_files.values() if not os.path.exists(path)]
# 
#     if missing:
#         st.error("Processed data files are missing. Please run f1analytics.py first.")
#         st.write("Missing files:", missing)
#         st.stop()
# 
#     results_5yr = pd.read_csv(required_files["results"])
#     pit_5yr = pd.read_csv(required_files["pit"])
#     laps_5yr = pd.read_csv(required_files["laps"])
#     qualifying_5yr = pd.read_csv(required_files["qualifying"])
# 
#     return results_5yr, pit_5yr, laps_5yr, qualifying_5yr
# 
# 
# results_5yr, pit_5yr, laps_5yr, qualifying_5yr = load_processed_data()
# 
# # -----------------------------
# # Sidebar filters
# # -----------------------------
# st.sidebar.header("Dashboard Filters")
# 
# available_years = sorted(results_5yr["year"].dropna().unique())
# selected_year = st.sidebar.selectbox("Select Season", available_years)
# 
# season_data = results_5yr[results_5yr["year"] == selected_year].copy()
# 
# available_teams = ["All Teams"] + sorted(season_data["constructor_name"].dropna().unique().tolist())
# selected_team = st.sidebar.selectbox("Select Constructor", available_teams)
# 
# if selected_team != "All Teams":
#     season_data = season_data[season_data["constructor_name"] == selected_team].copy()
# 
# # -----------------------------
# # KPI metrics
# # -----------------------------
# total_races = season_data["raceId"].nunique()
# total_drivers = season_data["driver_name"].nunique()
# total_constructors = season_data["constructor_name"].nunique()
# total_points = round(season_data["points"].sum(), 2)
# 
# col1, col2, col3, col4 = st.columns(4)
# 
# col1.metric("Total Races", total_races)
# col2.metric("Total Drivers", total_drivers)
# col3.metric("Total Constructors", total_constructors)
# col4.metric("Total Points", total_points)
# 
# st.divider()
# 
# # -----------------------------
# # Top drivers and constructors
# # -----------------------------
# left_col, right_col = st.columns(2)
# 
# with left_col:
#     st.subheader(f"Top Drivers by Points - {int(selected_year)}")
# 
#     driver_points = (
#         season_data
#         .groupby("driver_name")["points"]
#         .sum()
#         .sort_values(ascending=False)
#         .reset_index()
#     )
# 
#     fig, ax = plt.subplots(figsize=(10, 6))
#     sns.barplot(data=driver_points.head(10), x="points", y="driver_name", ax=ax)
#     ax.set_title(f"Top 10 Drivers by Points - {int(selected_year)}")
#     ax.set_xlabel("Total Points")
#     ax.set_ylabel("Driver")
#     ax.grid(axis="x", alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# with right_col:
#     st.subheader(f"Constructor Points - {int(selected_year)}")
# 
#     constructor_points = (
#         season_data
#         .groupby("constructor_name")["points"]
#         .sum()
#         .sort_values(ascending=False)
#         .reset_index()
#     )
# 
#     fig, ax = plt.subplots(figsize=(10, 6))
#     sns.barplot(data=constructor_points, x="points", y="constructor_name", ax=ax)
#     ax.set_title(f"Constructor Points - {int(selected_year)}")
#     ax.set_xlabel("Total Points")
#     ax.set_ylabel("Constructor")
#     ax.grid(axis="x", alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Five-year trends
# # -----------------------------
# st.subheader("Five-Year Performance Trends")
# 
# trend_col1, trend_col2 = st.columns(2)
# 
# with trend_col1:
#     total_driver_points = (
#         results_5yr
#         .groupby("driver_name")["points"]
#         .sum()
#         .sort_values(ascending=False)
#         .reset_index()
#     )
# 
#     top_drivers = total_driver_points.head(5)["driver_name"].tolist()
# 
#     driver_trend = (
#         results_5yr
#         .groupby(["year", "driver_name"])["points"]
#         .sum()
#         .reset_index()
#     )
# 
#     driver_trend = driver_trend[driver_trend["driver_name"].isin(top_drivers)]
# 
#     fig, ax = plt.subplots(figsize=(10, 6))
#     sns.lineplot(data=driver_trend, x="year", y="points", hue="driver_name", marker="o", ax=ax)
#     ax.set_title("Top Driver Points Trend: 2020–2024")
#     ax.set_xlabel("Season")
#     ax.set_ylabel("Points")
#     ax.grid(True, alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# with trend_col2:
#     total_constructor_points = (
#         results_5yr
#         .groupby("constructor_name")["points"]
#         .sum()
#         .sort_values(ascending=False)
#         .reset_index()
#     )
# 
#     top_constructors = total_constructor_points.head(5)["constructor_name"].tolist()
# 
#     constructor_trend = (
#         results_5yr
#         .groupby(["year", "constructor_name"])["points"]
#         .sum()
#         .reset_index()
#     )
# 
#     constructor_trend = constructor_trend[constructor_trend["constructor_name"].isin(top_constructors)]
# 
#     fig, ax = plt.subplots(figsize=(10, 6))
#     sns.lineplot(data=constructor_trend, x="year", y="points", hue="constructor_name", marker="o", ax=ax)
#     ax.set_title("Top Constructor Points Trend: 2020–2024")
#     ax.set_xlabel("Season")
#     ax.set_ylabel("Points")
#     ax.grid(True, alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Race wins and grid vs finish
# # -----------------------------
# analysis_col1, analysis_col2 = st.columns(2)
# 
# with analysis_col1:
#     st.subheader(f"Race Wins by Driver - {int(selected_year)}")
# 
#     wins = season_data[season_data["positionOrder"] == 1]
# 
#     driver_wins = (
#         wins
#         .groupby("driver_name")
#         .size()
#         .sort_values(ascending=False)
#         .reset_index(name="wins")
#     )
# 
#     if driver_wins.empty:
#         st.warning("No race win data available.")
#     else:
#         fig, ax = plt.subplots(figsize=(10, 6))
#         sns.barplot(data=driver_wins, x="wins", y="driver_name", ax=ax)
#         ax.set_title(f"Race Wins by Driver - {int(selected_year)}")
#         ax.set_xlabel("Number of Wins")
#         ax.set_ylabel("Driver")
#         ax.grid(axis="x", alpha=0.3)
#         st.pyplot(fig, use_container_width=True)
# 
# with analysis_col2:
#     st.subheader(f"Grid Position vs Final Position - {int(selected_year)}")
# 
#     grid_vs_finish = season_data[season_data["grid"] > 0].copy()
# 
#     if grid_vs_finish.empty:
#         st.warning("No grid data available.")
#     else:
#         fig, ax = plt.subplots(figsize=(10, 6))
#         sns.scatterplot(
#             data=grid_vs_finish,
#             x="grid",
#             y="positionOrder",
#             hue="constructor_name",
#             ax=ax
#         )
#         ax.set_title(f"Grid Position vs Final Position - {int(selected_year)}")
#         ax.set_xlabel("Starting Grid Position")
#         ax.set_ylabel("Final Race Position")
#         ax.grid(True, alpha=0.3)
#         ax.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
#         st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Pit stop analysis
# # -----------------------------
# st.subheader(f"Pit Stop Analysis - {int(selected_year)}")
# 
# pit_season = pit_5yr[pit_5yr["year"] == selected_year].copy()
# 
# avg_pit = (
#     pit_season
#     .groupby("driver_name")["pit_seconds"]
#     .mean()
#     .sort_values()
#     .reset_index()
# )
# 
# if avg_pit.empty:
#     st.warning("No pit stop data available.")
# else:
#     fig, ax = plt.subplots(figsize=(12, 6))
#     sns.barplot(data=avg_pit.head(10), x="pit_seconds", y="driver_name", ax=ax)
#     ax.set_title(f"Fastest Average Pit Stop Duration - {int(selected_year)}")
#     ax.set_xlabel("Average Pit Stop Time Seconds")
#     ax.set_ylabel("Driver")
#     ax.grid(axis="x", alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Qualifying analysis
# # -----------------------------
# st.subheader(f"Qualifying Analysis - {int(selected_year)}")
# 
# qualifying_season = qualifying_5yr[qualifying_5yr["year"] == selected_year].copy()
# 
# avg_qualifying = (
#     qualifying_season
#     .groupby("driver_name")["position"]
#     .mean()
#     .sort_values()
#     .reset_index()
# )
# 
# if avg_qualifying.empty:
#     st.warning("No qualifying data available.")
# else:
#     fig, ax = plt.subplots(figsize=(12, 6))
#     sns.barplot(data=avg_qualifying.head(10), x="position", y="driver_name", ax=ax)
#     ax.set_title(f"Best Average Qualifying Position - {int(selected_year)}")
#     ax.set_xlabel("Average Qualifying Position")
#     ax.set_ylabel("Driver")
#     ax.grid(axis="x", alpha=0.3)
#     st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Lap time comparison
# # -----------------------------
# st.subheader("Lap Time Comparison")
# 
# available_races = sorted(
#     laps_5yr[laps_5yr["year"] == selected_year]["race_name"].dropna().unique()
# )
# 
# if len(available_races) == 0:
#     st.warning("No lap time data available.")
# else:
#     selected_race = st.selectbox("Select Race", available_races)
# 
#     race_laps = laps_5yr[
#         (laps_5yr["year"] == selected_year) &
#         (laps_5yr["race_name"] == selected_race)
#     ].copy()
# 
#     available_drivers = sorted(race_laps["driver_name"].dropna().unique())
# 
#     selected_drivers = st.multiselect(
#         "Select Drivers",
#         available_drivers,
#         default=available_drivers[:3]
#     )
# 
#     selected_laps = race_laps[race_laps["driver_name"].isin(selected_drivers)].copy()
# 
#     if selected_laps.empty:
#         st.warning("Please select at least one driver.")
#     else:
#         fig, ax = plt.subplots(figsize=(12, 6))
#         sns.lineplot(
#             data=selected_laps,
#             x="lap",
#             y="lap_seconds",
#             hue="driver_name",
#             ax=ax
#         )
#         ax.set_title(f"Lap Time Comparison - {selected_race} {int(selected_year)}")
#         ax.set_xlabel("Lap Number")
#         ax.set_ylabel("Lap Time Seconds")
#         ax.grid(True, alpha=0.3)
#         st.pyplot(fig, use_container_width=True)
# 
#         fig, ax = plt.subplots(figsize=(12, 6))
#         sns.boxplot(
#             data=selected_laps,
#             x="driver_name",
#             y="lap_seconds",
#             ax=ax
#         )
#         ax.set_title(f"Lap Time Consistency - {selected_race} {int(selected_year)}")
#         ax.set_xlabel("Driver")
#         ax.set_ylabel("Lap Time Seconds")
#         ax.tick_params(axis="x", rotation=30)
#         ax.grid(axis="y", alpha=0.3)
#         st.pyplot(fig, use_container_width=True)
# 
# st.divider()
# 
# # -----------------------------
# # Data preview
# # -----------------------------
# st.subheader("Data Preview")
# 
# preview_cols = [
#     "year",
#     "race_name",
#     "driver_name",
#     "constructor_name",
#     "grid",
#     "positionOrder",
#     "points"
# ]
# 
# preview_cols = [col for col in preview_cols if col in season_data.columns]
# 
# st.dataframe(
#     season_data[preview_cols].head(50),
#     use_container_width=True
# )

!pip install streamlit pandas numpy matplotlib seaborn

!streamlit run F1app.py --server.port 8501 --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false > streamlit.log 2>&1 &

!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared
!./cloudflared tunnel --url http://localhost:8501 --no-autoupdate